import * as z from "zod";
export const jsonSchema = z.object({
    totalCount: z.number(),
    totalPeriod: z.enum(["install-time"]),
    trackerCompaniesPeriod: z.enum(["last-hour"]),
    trackerCompanies: z.array(
        z.object({
            name: z.string(),
            displayName: z.string(),
            count: z.number(),
            favicon: z.string().default(() => 'Shield.png')
        })
    )
});

export const icons = [
    "adjust",
    "adobe",
    "amazon",
    "amplitude",
    "appnexus",
    "appsflyer",
    "beeswax",
    "branchmetrics",
    "braze",
    "bugsnag",
    "chartbeat",
    "comscore",
    "criteo",
    "facebook",
    "google",
    "googleadsgoogle",
    "googleanalyticsgoogle",
    "indexexchange",
    "instagramfacebook",
    "iponweb",
    "kochava",
    "linkedin",
    "liveramp",
    "magnite",
    "mediamath",
    "microsoft",
    "mixpanel",
    "neustar",
    "newrelic",
    "openx",
    "oracle",
    "outbrain",
    "pinterest",
    "pubmatic",
    "quantcast",
    "rythmone",
    "salesforce",
    "sharetrough",
    "smaato",
    "spotx",
    "taboola",
    "tapad",
    "thenielsencompany",
    "thetradedesk",
    "twitter",
    "urbanairship",
    "verizonmedia",
    "warnermedia",
    "xaxis",
    "yahoojapan",
    "yandex",
    "youtubegoogle",
    "zeotap",
]
